INSERT INTO `reslow`.`product_category_tb` (`product_category_pk`, `category`) VALUES ('1', '가구/인테리어');
INSERT INTO `reslow`.`product_category_tb` (`product_category_pk`, `category`) VALUES ('2', '여성잡화');
INSERT INTO `reslow`.`product_category_tb` (`product_category_pk`, `category`) VALUES ('3', '여성의류');
INSERT INTO `reslow`.`product_category_tb` (`product_category_pk`, `category`) VALUES ('4', '남성잡화');
INSERT INTO `reslow`.`product_category_tb` (`product_category_pk`, `category`) VALUES ('5', '남성의류');
INSERT INTO `reslow`.`product_category_tb` (`product_category_pk`, `category`) VALUES ('6', '뷰티/미용');
INSERT INTO `reslow`.`product_category_tb` (`product_category_pk`, `category`) VALUES ('7', '반려동물용품');
INSERT INTO `reslow`.`product_category_tb` (`product_category_pk`, `category`) VALUES ('8', '생활용품');
INSERT INTO `reslow`.`product_category_tb` (`product_category_pk`, `category`) VALUES ('9', '기타');
